name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: "Check with Prettier"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Check with Prettier
        run: npx prettier --check --ignore-path .prettierignore '**/*.(yml|js|ts|json)'
